# docker-compose.yml

version: '3.8'

services:
  # Backend Service (Laravel)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hris_backend
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    networks:
      - hris-network
    depends_on:
      - db

  # Frontend Service (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hris_frontend
    networks:
      - hris-network

  # Database Service (MySQL)
  db:
    image: mysql:8.0
    container_name: hris_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - hris-network

  # Nginx Web Server
  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: hris_webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443" # Jika nanti mau setup SSL
    volumes:
      - ./backend/public:/var/www/public # Volume untuk Laravel public
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - hris-network
    depends_on:
      - backend
      - frontend

networks:
  hris-network:
    driver: bridge

volumes:
  db_data:
    driver: local
