import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../lib/authContext"; // import di sini

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geist.className}`}>
        <AuthProvider>
          <div className="max-w-6xl mx-auto px-4">
            <main className="mt-8">{children}</main>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
