name: CD - Deploy to Production Server

# Pemicu: Jalankan setelah workflow 'CI - Build and Push Docker Images' berhasil
on:
  workflow_run:
    workflows: ["CI - Build and Push Docker Images"]
    types:
      - completed

jobs:
  deploy:
    # Jalankan pekerjaan ini HANYA JIKA workflow CI berhasil
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    # Gunakan runner yang sudah kita instal di VM kita
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Navigate to project directory
        run: cd ~/hris-cmlabs # Sesuaikan dengan path proyek Anda di VM

      - name: Pull latest images from Docker Hub
        run: docker compose pull

      - name: Restart services with new images
        run: docker compose up -d
