name: Build and Deploy Frontend to Azure VM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Langkah 1: Mengunduh semua kode dari repositori
      - name: Checkout repository
        uses: actions/checkout@v4

      # Langkah 2: Setup Node.js untuk melakukan proses build
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Gunakan versi Node.js yang sesuai dengan proyek Anda

      # Langkah 3: Melakukan proses build (mengubah resep menjadi kue jadi)
      - name: Build Frontend Project
        run: |
          cd frontend
          npm install
          npm run build

      # Langkah 4: Menyalin HANYA HASIL BUILD ke server VM
      - name: Copy build output to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_SSH_HOST }}
          username: ${{ secrets.AZURE_SSH_USER }}
          key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
          port: 22
          # PENTING: Sumbernya sekarang adalah folder 'out' hasil build
          source: "frontend/out/"
          target: "/var/www/hris-frontend"
          strip_components: 1