# .github/workflows/deploy.yml

name: Deploy to Azure VM

on:
  push:
    branches:
      - main # Atau branch lain yang kamu gunakan untuk production

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Azure (Opsional, jika perlu interaksi lain dengan Azure)
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to VM via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /path/to/your/project/hris-cmlabs # Ganti dengan path di VM
          git pull origin main
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" > .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
          # Tambahkan variabel env lain yang diperlukan
          
          docker-compose -f docker-compose.yml up --build -d
          # Jalankan migrasi dan seeding setelah container up
          docker-compose exec backend php artisan migrate --force
          docker-compose exec backend php artisan db:seed --force # Jika ada
